export enum ErrorCode {
	BAD_REQUEST = 'BAD_REQUEST',
	UNAUTHORIZED = 'UNAUTHORIZED',
	INVALID_TOKEN = 'INVALID_TOKEN',
	TOKEN_EXPIRED = 'TOKEN_EXPIRED',
	AUTHENTICATION_REQUIRED = 'AUTHENTICATION_REQUIRED',
	INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
	FORBIDDEN = 'FORBIDDEN',
	INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',
	NOT_FOUND = 'NOT_FOUND',
	ROUTE_NOT_FOUND = 'ROUTE_NOT_FOUND',
	USER_NOT_FOUND = 'USER_NOT_FOUND',
	SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',
	METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED',
	CONFLICT = 'CONFLICT',
	EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
	PHONE_ALREADY_EXISTS = 'PHONE_ALREADY_EXISTS',
	PAYLOAD_TOO_LARGE = 'PAYLOAD_TOO_LARGE',
	UNSUPPORTED_MEDIA_TYPE = 'UNSUPPORTED_MEDIA_TYPE',
	VALIDATION_ERROR = 'VALIDATION_ERROR',
	REQUIRED_FIELD_MISSING = 'REQUIRED_FIELD_MISSING',
	INVALID_FIELD_VALUE = 'INVALID_FIELD_VALUE',
	RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
	TOO_MANY_LOGIN_ATTEMPTS = 'TOO_MANY_LOGIN_ATTEMPTS',

	ACCOUNT_SUSPENDED = 'ACCOUNT_SUSPENDED',
	ACCOUNT_DELETED = 'ACCOUNT_DELETED',
	ACCOUNT_INACTIVE = 'ACCOUNT_INACTIVE',
	ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
	EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
	PHONE_NOT_VERIFIED = 'PHONE_NOT_VERIFIED',

	INVALID_CURRENT_PASSWORD = 'INVALID_CURRENT_PASSWORD',
	WEAK_PASSWORD = 'WEAK_PASSWORD',
	PASSWORD_PREVIOUSLY_USED = 'PASSWORD_PREVIOUSLY_USED',
	INVALID_RESET_TOKEN = 'INVALID_RESET_TOKEN',
	INVALID_VERIFICATION_TOKEN = 'INVALID_VERIFICATION_TOKEN',
	INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
	SESSION_REVOKED = 'SESSION_REVOKED',

	INTERNAL_ERROR = 'INTERNAL_ERROR',
	DATABASE_ERROR = 'DATABASE_ERROR',
	SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
	TIMEOUT = 'TIMEOUT',
}

export type AppError = {
	readonly type: string | ErrorCode;
	readonly message: string;
};

export type HttpErrorResponse = {
	readonly statusCode: number;
	readonly message: string;
	readonly errorCode: ErrorCode;
	readonly cause?: string;
	readonly causes?: readonly string[];
	readonly url: string;
	readonly datetime: string;
};
